# بيانات تجريبية (Mock). لما الـ Database تجهز، بدّل الملف ده بـ Queries.
CATEGORIES = ["Worship", "Jurisprudence", "Creed", "Ethics & Society"]

TERMS = [
 {"id": 1, "ar": "الزَّكَاة", "en": "Zakat", "es": "La Zakat", "translit": "az-Zakāh",
  "gloss_en": "Obligatory Charity", "gloss_es": "Limosna obligatoria",
  "root": "ز-ك-و", "root_latin": "Z-K-W", "category": "Worship", "sources": 3, "related_count": 8,
  "def_ar": "الزَّكَاةُ عبادةٌ ماليّةٌ واجبةٌ على المسلمين المستحقّين بشروطٍ معلومة، وهي أحد أركان الإسلام الخمسة.",
  "def_en": "An obligatory form of almsgiving and one of the Five Pillars of Islam, levied on qualifying wealth held for one full lunar year to purify property and foster communal equity.",
  "def_es": "Una forma obligatoria de caridad y uno de los cinco pilares del Islam, instituida para purificar la riqueza y socorrer a los colectivos vulnerables.",
  "specs": [("Statutory rate", "ربع العشر", "2.5%"), ("Holding period", "حول كامل", "1 full lunar year"), ("Minimum exemption", "النصاب", "85g gold / 595g silver")],
  "related": ["Sadaqah", "Nisab", "Zakat al-Fitr"], "refs": ["Al-Mawsu'a al-Fiqhiyyah al-Kuwaytiyyah, Vol. 23"]},
 {"id": 2, "ar": "الصَّلَاة", "en": "Salah", "es": "La oración", "translit": "aṣ-Ṣalāh",
  "gloss_en": "Ritual Prayer", "gloss_es": "Plegaria ritual",
  "root": "ص-ل-و", "root_latin": "Ṣ-L-W", "category": "Worship", "sources": 4, "related_count": 12,
  "def_ar": "الصَّلَاةُ ركنٌ من أركان الإسلام، وهي أقوالٌ وأفعالٌ مخصوصة تبدأ بالتكبير وتنتهي بالتسليم.",
  "def_en": "The second pillar of Islam, consisting of prescribed physical, oral, and spiritual prayers performed five times daily facing Mecca.",
  "def_es": "El segundo pilar del Islam, que consiste en oraciones físicas, orales y espirituales prescritas, realizadas cinco veces al día.",
  "specs": [], "related": ["Wudu", "Sujud", "Ruku"], "refs": []},
 {"id": 3, "ar": "الصَّوْم", "en": "Sawm", "es": "El ayuno", "translit": "aṣ-Ṣawm",
  "gloss_en": "Fasting", "gloss_es": "Abstención ritual",
  "root": "ص-و-م", "root_latin": "Ṣ-W-M", "category": "Worship", "sources": 3, "related_count": 6,
  "def_ar": "الصَّوْمُ الإمساك عن المفطّرات من طلوع الفجر إلى غروب الشمس بنيّة التعبّد.",
  "def_en": "The devotional abstention from food, drink, and intimacy from dawn until sunset during Ramadan and on voluntary occasions.",
  "def_es": "La abstención devocional de comida, bebida e intimidad desde el amanecer hasta la puesta del sol durante Ramadán.",
  "specs": [], "related": ["Ramadan", "Iftar"], "refs": []},
 {"id": 4, "ar": "التَّوْحِيد", "en": "Tawhid", "es": "Tawhid", "translit": "at-Tawḥīd",
  "gloss_en": "Divine Oneness", "gloss_es": "Monoteísmo islámico",
  "root": "و-ح-د", "root_latin": "W-Ḥ-D", "category": "Creed", "sources": 5, "related_count": 15,
  "def_ar": "التَّوْحِيدُ إفراد الله تعالى بالربوبية والألوهية والأسماء والصفات.",
  "def_en": "The fundamental concept of the indivisible oneness and unique sovereignty of God in Islamic theology.",
  "def_es": "El concepto fundamental de la unicidad indivisible y la soberanía única de Dios en la teología islámica.",
  "specs": [], "related": ["Shirk", "Iman"], "refs": []},
]
